"""Education table created

Revision ID: 06680677f687
Revises: 6734f1eb9e6a
Create Date: 2021-09-14 14:50:48.495252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06680677f687'
down_revision = '6734f1eb9e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_year', sa.String(length=100), nullable=True),
    sa.Column('experience_place', sa.String(length=100), nullable=True),
    sa.Column('experience_title', sa.String(length=100), nullable=True),
    sa.Column('experience_desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience')
    # ### end Alembic commands ###
