"""Maill table added

Revision ID: 0ab48ed7423e
Revises: 682d4367a97f
Create Date: 2021-09-18 01:14:40.804614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab48ed7423e'
down_revision = '682d4367a97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_name', sa.String(length=100), nullable=True),
    sa.Column('mail_subject', sa.String(length=100), nullable=True),
    sa.Column('mail_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail')
    # ### end Alembic commands ###
