"""Education table created

Revision ID: 0c872576e8bb
Revises: 614ae1c7ad71
Create Date: 2021-09-13 01:26:50.692024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c872576e8bb'
down_revision = '614ae1c7ad71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education_year', sa.String(length=100), nullable=True),
    sa.Column('education_place', sa.String(length=100), nullable=True),
    sa.Column('education_title', sa.String(length=100), nullable=True),
    sa.Column('education_desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education')
    # ### end Alembic commands ###
