"""Service table added

Revision ID: 16cb415765a8
Revises: 71c9dd5748c5
Create Date: 2021-09-12 02:44:46.192668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cb415765a8'
down_revision = '71c9dd5748c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_title', sa.String(length=100), nullable=True),
    sa.Column('service_desc', sa.String(length=100), nullable=True),
    sa.Column('service_icon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product')
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('service')
    # ### end Alembic commands ###
