"""Maill table updated

Revision ID: 415428ba1c87
Revises: 0ab48ed7423e
Create Date: 2021-09-18 01:24:13.412229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415428ba1c87'
down_revision = '0ab48ed7423e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail', sa.Column('mail_message', sa.String(length=100), nullable=True))
    op.drop_column('mail', 'mail_subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail', sa.Column('mail_subject', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('mail', 'mail_message')
    # ### end Alembic commands ###
