"""Table name changed

Revision ID: 56fe758ebbb7
Revises: 415428ba1c87
Create Date: 2021-09-18 14:20:44.490365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fe758ebbb7'
down_revision = '415428ba1c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_name', sa.String(length=100), nullable=True),
    sa.Column('mail_message', sa.String(length=100), nullable=True),
    sa.Column('mail_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mail_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mail_address', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mail_message', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contact')
    # ### end Alembic commands ###
