"""Testimotional table created

Revision ID: 614ae1c7ad71
Revises: 16cb415765a8
Create Date: 2021-09-12 16:08:48.263033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614ae1c7ad71'
down_revision = '16cb415765a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimotional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testimotional_content', sa.String(length=100), nullable=True),
    sa.Column('testimotional_writer', sa.String(length=100), nullable=True),
    sa.Column('writer_img', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimotional')
    # ### end Alembic commands ###
