"""Social media table created

Revision ID: 682d4367a97f
Revises: aa1b45e0ec6e
Create Date: 2021-09-14 15:49:36.453842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682d4367a97f'
down_revision = 'aa1b45e0ec6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_name', sa.String(length=100), nullable=True),
    sa.Column('social_link', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social')
    # ### end Alembic commands ###
